---

- name: Download neofs-cli binary
  ansible.builtin.get_url:
    url: '{{ neofs_storage__cli_bin_url }}'
    dest: '{{ neofs_storage__cli_bin_path }}'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: neofs_storage__binaries_download | bool
  register: download_result
  retries: 5
  delay: 5
  until: not download_result.failed
  ignore_errors: '{{ ansible_check_mode }}'
