---

- name: Copy TLS key & certificate
  block:
    - name: Copy TLS key
      ansible.builtin.copy:
        content: "{{ neofs_storage__tls_key_path }}"
        dest: "{{ neofs_storage__tls_key }}"
        owner: 'root'
        group: "{{ neofs_storage__group }}"
        mode: '0640'
    - name: Copy TLS cert
      ansible.builtin.copy:
        content: "{{ neofs_storage__tls_cert_path }}"
        dest: "{{ neofs_storage__tls_cert }}"
        owner: 'root'
        group: "{{ neofs_storage__group }}"
        mode: '0640'
  when: neofs_storage__tls_enabled
  notify: [ 'Restart NeoFS Storage' ]
