---

- name: Create NeoFS Storage group
  ansible.builtin.group:
    name: '{{ neofs_storage__group }}'
    system: yes

- name: Create NeoFS Storage user
  ansible.builtin.user:
    name: '{{ neofs_storage__user }}'
    group: '{{ neofs_storage__group }}'
    password: '*'
    shell: '/usr/sbin/nologin'
    home: '{{ neofs_storage__data_dir }}'
    system: yes
    skeleton: no
