---

- name: Create NeoFS Storage group
  ansible.builtin.group:
    name: "{{ neofs_storage__group }}"
    system: yes

- name: Create NeoFS Storage user
  ansible.builtin.user:
    name: "{{ neofs_storage__user }}"
    group: "{{ neofs_storage__group }}"
    password: '*'
    shell: '/usr/sbin/nologin'
    home: "{{ neofs_storage__data_dir }}"
    system: yes
    skeleton: no

- name: Get UID for NeoFS Storage user
  ansible.builtin.getent:
    database: passwd
    key: "{{ neofs_storage__user }}"

- name: Get GID for NeoFS Storage user
  ansible.builtin.getent:
    database: group
    key: "{{ neofs_storage__group }}"
