---

- name: Copy NeoFS Storage wallet
  ansible.builtin.copy:
    content: '{{ neofs_storage__wallet_struct | to_nice_json(ensure_ascii=False) }}'
    dest: '{{ neofs_storage__wallet_path }}'
    owner: 'root'
    group: '{{ neofs_storage__group }}'
    mode: '0640'
  notify: [ 'Restart NeoFS Storage' ]
